name: Validate Commit message

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
    # branches: [master, release**]
    branches: [master]

jobs:
  validate-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with full history
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PA_TOKEN }}
          fetch-depth: 0
      - run: git fetch
      - name: Validate commit messages
        run: |
          commits=$(git log --format=%B ${{ github.event.pull_request.base.sha }}..${{ github.sha }})
          for commit in "$commits"; do
            echo "Handling commit: $commit"
            echo "$commit" | grep -E '^(FEATURE|IMPROVEMENT|BUG)\(TICKET-[0-9]{4}\): .{1,}$' || exit 1
            echo "$commit" | awk 'NR==2 { exit ($0 != "" ? 1 : 0) }' # Check for a blank second line

            body=$(echo "$commit" | sed -n '3,$p')
            if [ ! -z "$body" ]; then
              echo "$body" | while IFS= read -r line; do
                [[ ${#line} -gt 72 ]] && echo "Line exceeds 72 characters: $line" && exit 1
              done
            fi
          done
