name: Validate Commit message

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
    # branches: [master, release**]
    branches: [master]

jobs:
  validate-commits:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./.github/workflows/scripts
    steps:
      - name: Checkout repository with full history
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PA_TOKEN }}
          fetch-depth: 0
      - run: git fetch
      - name: Validate commit messages
        run: ./validate_commits.sh ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}